package codegen;

public enum SyntheticFunction {
    ALLOCATE_ARRAY,
    ALLOCATE_NESTED_ARRAY,
    CONCAT_STRING_STRING,
    CONCAT_STRING_BOOL,
    CONCAT_BOOL_STRING,
    CONCAT_STRING_INT,
    CONCAT_INT_STRING,
    LOAD_STRING_TRUE,
    LOAD_STRING_FALSE,
    LOAD_STRING_INT,
}
